name: Build Rootless Tweak

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        uses: Randomblock1/theos-action@v1

      - name: Verify Files
        run: |
          ls -la
          find . -name "*.a"

      - name: Build
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: Rootless-DEB
          path: packages/*.deb
